// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://povwwxkhcjxjhdkgrzqf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvdnd3eGtoY2p4amhka2dyenFmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5Mjc5MzMsImV4cCI6MjA2ODUwMzkzM30.wrhgUVqUmmhQ5_-KlHDlMzAFOP025V3yTYk0ejaee3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});