// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pwgpzzjvlufpweoricyv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB3Z3B6emp2bHVmcHdlb3JpY3l2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5MTA4MzEsImV4cCI6MjA2ODQ4NjgzMX0.KpUr80Yqid7oJtGqnNpSGrIOzs2oP-mqzI10FD4p1gE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});